spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:29092

    consumer:
      group-id: notification-service
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          com.ecommerce.payment.event.PaymentCompletedEvent:com.ecommerce.notification.event.PaymentCompletedEvent,
          com.ecommerce.order.event.OrderCreatedEvent:com.ecommerce.notification.event.OrderCreatedEvent

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/