spring:

  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://customer-postgres:5432/customer_db
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  flyway:
    enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ecommerce

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
